helmCharts:
- name: cert-manager
  version: 1.6.1
  namespace: dns-infra
  repo: https://charts.jetstack.io
  releaseName: cert-manager
  valuesInline: 
    installCRDs: true 
    rbac:
      create: true
