{{- if .Values.certificate.create -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "cdevents-controller.fullname" . }}
  labels:
    {{- include "cdevents-controller.labels" . | nindent 4 }}
spec:
  dnsNames:
  {{- range .Values.certificate.dnsNames }}
    - {{ . | quote }}
  {{- end }}
  secretName: {{ template "cdevents-controller.tlsSecretName" . }}
  issuerRef:
  {{- .Values.certificate.issuerRef | toYaml | trimSuffix "\n" | nindent 4 }}
{{- end }}
